# -*- coding: utf-8 -*-
"""Twitter _Sentiment_Dashboard.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZNC_YycFdYx-LviawHOXRNSs0LgI2Pm
"""

print("Twitter Sentiment Analysis Project")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

data = {
    "Tweet":["Ilove this new phone, amazing experience",
             "Worst service ever,very disappointed",
             "The product is okay, nothing special",
             "Amazing quality and fast delivery",
             "I hate this app, it is useless"]
}
df = pd.DataFrame(data)
df

import re
def clean_text(text):
  text = re.sub (r"http\S+", "", text)
  text = re.sub(r"@\w", "", text)
  text = re.sub(r"#\w+", "", text)
  text = re.sub(r"[^A-Za-z\s]", "", text)
  text = text.lower()
  text = text.strip()
  return text
  df["Clean_Tweet"] = df["Tweet"].apply(clean_text)
  df

print(df.columns)

df["Clean_Tweet"] = df["Tweet"].str.lower()
df.head()

!pip install vaderSentiment

df["Sentiment"] = "Neutral"
df.loc[df["Clean_Tweet"].str.contains("love|amazing|quality", case=False),
       "Sentiment"] = "Positive"
df.loc[df["Clean_Tweet"].str.contains("worst|hate|useless|disappointes",case=False), "Sentiment"] = "Negative"
df

import matplotlib.pyplot as plt
sentiment_count = df["Sentiment"].value_counts()
plt.figure(figsize=(6,4))
sentiment_count.plot(kind="bar")
plt.xlabel("Sentiment")
plt.ylable("Number of Tweets")
plt.title("Tweet Sentiment Analysis")
plt.show()

!pip install wordcloud

from wordcloud import WordCloud
text = " ".join(df["Clean_Tweet"])
wordcloud = WordCloud(width=800,height=400).generate(text)
plt.figure(figsize=(10,5))
plt.imshow(wordcloud)
plt.axis("off")
plt.show()

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# 
# st.title("Twitter Sentiment Analysis Dashboard")
# st.write("Sentiment Analysis using NLP")
# 
# 
# data = {
#     "Sentiment":
#     df["Sentiment"].value_counts().index,"Count":
#     df["Sentiment"].value_counts().values
# }
# chart_df = pd.DataFrame(data)
# st.subheader("Sentiment Count")
# st.dataframe(chart_df)
# fig, ax = plt.subplots()
# ax.bar(chart_df["Sentiment"],
#        chart_df["Count"])
# plt.xlabel("Sentiment")
# plt.ylabel("Count")
# st.pyplot(fig)

!streamlit run app.py &

!streamlit run app.py --server.address=0.0.0.0 --server.port=8501 &

!ls